# Generated by Django 2.2 on 2021-09-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitalData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='biotag',
            name='memberImage',
            field=models.URLField(default='https://i.picsum.photos/id/1005/5760/3840.jpg?hmac=2acSJCOwz9q_dKtDZdSB-OIK1HUcwBeXco_RMMTUgfY'),
        ),
    ]
