# Generated by Django 2.2 on 2021-09-17 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VitalData', '0002_auto_20210916_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='physicalvital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hip_circum', models.CharField(blank=True, max_length=50, null=True)),
                ('waist_cicrum', models.CharField(blank=True, max_length=50, null=True)),
                ('whr_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
