# Generated by Django 2.2 on 2021-09-24 14:10

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('VitalData', '0004_auto_20210917_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='biotag',
            name='alcohol',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biotag',
            name='coffee',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biotag',
            name='other',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biotag',
            name='sexual_orientation',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biotag',
            name='surgery',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biotag',
            name='tobacco',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
